--- 
# LDAP connections
connections:
  example_connection_1:
    username: "cn=Directory Manager"
    password: "password"
    host: ldap.yourdomain.com
    port: 389
    basedn: "ou=smallpeople,ou=qa,dc=socialcast,dc=com"
    filter: "(mail=*)"
  example_connection_2:
    username: "cn=Directory Manager"
    password: "password"
    host: ldap.yourdomain.com
    port: 389
    basedn: "ou=tinypeople,ou=qa,dc=yourdomain,dc=com"
    filter: "(mail=*)"
  example_encrypted_connection:
    username: "cn=Directory Manager"
    password: "password"
    host: ldap.yourdomain.com
    port: 389
    basedn: "ou=largepeople,ou=qa,dc=yourdomain,dc=com"
    filter: "(mail=*)"
    encryption: simple_tls


# LDAP attribute mappings
mappings: 
  first_name: givenName
  last_name: sn
  email: mail
  # only use employee_number if the email is unknown
  # employee_number: emp_id
  # only use unique_identifier if you do not wish to use email as the main user identification method
  # unique_identifier: samaccountname


# general script options
options:
  # cleanup the extracted ldap data file after run is complete
  delete_users_file: false
  # skip sending emails to newly activated users
  skip_emails: true
  # do not actually provision accounts
  # useful during testing
  test: true


# http options for connecting to Socialcast servers
http:
  timeout: 660
  # optional setting if script must connect to Socialcast server through a proxy
  # proxy: "http://username:password@proxy.company.com:3128"
